src/Entity/Invoice.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Helper\IdTrait;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="app_invoice",
 *     uniqueConstraints={
 *          @ORM\UniqueConstraint(name="number_type_year", columns={"number", "type", "year"})
 *     })
 * @ORM\Entity(repositoryClass="App\Repository\InvoiceRepository")
 * @UniqueEntity(fields={"type", "number", "year"}, message="notification.invoice_number_must_be_unique")
 */
class Invoice
{
    use IdTrait {
        IdTrait::__construct as IdTraitConstruct;
    }
    use TimestampableEntity;

    /**
     * @var Client|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank()
     * @Assert\Valid()
     */
    private $client;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=3)
     */
    private $number;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=10)
     *
     * @Assert\NotBlank()
     * @Assert\Choice(choices={"invoice", "credit"})
     */
    private $type;

    /**
     * @ORM\Column(type="date")
     *
     * @Assert\NotBlank()
     */
    private $issueDate;

    /**
     * @ORM\Column(type="date")
     */
    private $dueDate;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Address", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank()
     * @Assert\Valid()
     */
    private $address;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $amountExcludingTax;

    /**
     * @ORM\Column(type="float"))
     */
    private $taxRate;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $taxAmount;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $amountIncludingTax;

    /**
     * @ORM\Column(type="decimal", precision=15, scale=2)
     */
    private $amountPaid;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @Assert\Length(min=1)
     */
    private $comment;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @Assert\Length(min=1)
     */
    private $commentInternal;

    /**
     * @var Collection|InvoiceDetail[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\InvoiceDetail",
     *     mappedBy="invoice",
     *     orphanRemoval=true,
     *     cascade={"persist", "remove"})
     */
    private $details;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint")
     */
    private $year;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @Assert\Length(min=1, max=255)
     */
    private $orderNumber;

    /**
     * @var Invoice|null
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Invoice")
     */
    private $credit;

    public function __construct()
    {
        $this->IdTraitConstruct();
        $this->amountExcludingTax = '0.0';
        $this->amountIncludingTax = '0.0';
        $this->amountPaid = '0.0';
        $this->details = new ArrayCollection();
        $this->dueDate = new DateTime('+1 month');
        $this->issueDate = new DateTime();
        $this->taxRate = 0.2;
        $this->taxAmount = '0.0';
        $this->type = 'invoice';
        $this->year = (int) $this->issueDate->format('Y');
    }

    public function __toString(): string
    {
        return (string) $this->number;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getIssueDate(): DateTimeInterface
    {
        return $this->issueDate;
    }

    public function setIssueDate(DateTimeInterface $issueDate): self
    {
        $this->issueDate = $issueDate;
        $this->year = (int) $issueDate->format('Y');

        return $this;
    }

    public function getDueDate(): DateTimeInterface
    {
        return $this->dueDate;
    }

    public function setDueDate(DateTimeInterface $dueDate): self
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getAmountExcludingTax(): string
    {
        return $this->amountExcludingTax;
    }

    public function setAmountExcludingTax(string $amountExcludingTax): self
    {
        $this->amountExcludingTax = $amountExcludingTax;

        return $this;
    }

    public function getAmountIncludingTax(): string
    {
        return $this->amountIncludingTax;
    }

    public function setAmountIncludingTax(string $amountIncludingTax): self
    {
        $this->amountIncludingTax = $amountIncludingTax;

        return $this;
    }

    public function getAmountPaid(): string
    {
        return $this->amountPaid;
    }

    public function setAmountPaid(string $amountPaid): self
    {
        $this->amountPaid = $amountPaid;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCommentInternal(): ?string
    {
        return $this->commentInternal;
    }

    public function setCommentInternal(?string $commentInternal): self
    {
        $this->commentInternal = $commentInternal;

        return $this;
    }

    /**
     * @return Collection|InvoiceDetail[]
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(InvoiceDetail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details[] = $detail;
            $detail->setInvoice($this);
        }

        $this->updateAmounts();

        return $this;
    }

    public function updateAmounts(): void
    {
        $this->amountExcludingTax = '0';
        foreach ($this->details as $detail) {
            $this->amountExcludingTax = bcadd($this->amountExcludingTax, $detail->getAmountTotal(), 5);
        }
        $this->taxAmount = bcmul($this->amountExcludingTax, (string) $this->taxRate, 5);
        $this->amountIncludingTax = bcadd($this->amountExcludingTax, $this->taxAmount, 5);
    }

    public function removeDetail(InvoiceDetail $detail): self
    {
        if ($this->details->contains($detail)) {
            $this->details->removeElement($detail);
            // set the owning side to null (unless already changed)
            if ($detail->getInvoice() === $this) {
                $detail->setInvoice(null);
            }
        }

        $this->updateAmounts();

        return $this;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTaxAmount(): string
    {
        return $this->taxAmount;
    }

    public function setTaxAmount(string $taxAmount): self
    {
        $this->taxAmount = $taxAmount;

        return $this;
    }

    public function getTaxRate(): float
    {
        return $this->taxRate;
    }

    public function setTaxRate(float $taxRate): self
    {
        $this->taxRate = $taxRate;

        return $this;
    }

    public function getNumberComplete(): string
    {
        return sprintf('%s%s', $this->issueDate->format('ym'), $this->number);
    }

    public function getYear(): int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    public function setOrderNumber(?string $orderNumber): self
    {
        $this->orderNumber = $orderNumber;

        return $this;
    }

    public function getCredit(): ?self
    {
        return $this->credit;
    }

    public function setCredit(?self $credit): self
    {
        $this->credit = $credit;

        return $this;
    }
}

src/Entity/RecordDetailInterface.php
<?php

namespace App\Entity;

interface RecordDetailInterface
{
    public function getAmountTotal(): string;

    public function getAmountUnit(): string;

    public function getDesignation(): ?string;

    public function getQuantity(): float;
}

src/Controller/InvoiceController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Client;
use App\Entity\Invoice;
use App\Entity\InvoiceDetail;
use App\Form\Type\InvoiceDeleteType;
use App\Form\Type\InvoiceSearchType;
use App\Form\Type\InvoiceType;
use App\Model\InvoicePDF;
use App\Repository\InvoiceRepository;
use App\Service\SearchManager;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/invoice")
 * @IsGranted("ROLE_ADMIN")
 */
final class InvoiceController extends AbstractController
{
    /**
     * @Route("/{uuid}/delete",
     *     name="app_invoice_delete",
     *     methods={"GET", "POST"})
     */
    public function delete(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Invoice $invoice
    ): Response {
        $formDelete = $this->createForm(InvoiceDeleteType::class, $invoice);
        $formDelete->handleRequest($request);

        if ($formDelete->isSubmitted() && $formDelete->isValid()) {
            $em->remove($invoice);
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.invoice_removed'));

            return $this->redirectToRoute('app_invoice_index');
        }

        return $this->render(
            'invoice/delete.html.twig',
            [
                'formDelete' => $formDelete->createView(),
                'invoice' => $invoice,
            ]
        );
    }

    /**
     * @Route("/{uuid}/edit",
     *     name="app_invoice_edit",
     *     methods={"GET", "POST"})
     */
    public function edit(
        Request $request,
        TranslatorInterface $translator,
        EntityManagerInterface $em,
        Invoice $invoice
    ): Response {
        $formEdit = $this->createForm(InvoiceType::class, $invoice);
        $formEdit->handleRequest($request);

        if ($formEdit->isSubmitted() && $formEdit->isValid()) {
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.invoice_updated'));

            return $this->redirectToRoute('app_invoice_show', ['uuid' => $invoice->getUuid()]);
        }

        return $this->render(
            'invoice/edit.html.twig',
            [
                'formEdit' => $formEdit->createView(),
                'invoice' => $invoice,
            ]
        );
    }

    /**
     * @Route("/",
     *     name="app_invoice_index",
     *     methods={"GET", "POST"})
     */
    public function index(Request $request, SearchManager $sm, InvoiceRepository $invoiceRepository): Response
    {
        $search = $sm->find($this->getUser(), 'app_invoice_index');

        $formSearch = $this->createForm(InvoiceSearchType::class);

        if ($sm->handleRequest($search, $request, $formSearch)) {
            return $this->redirectToRoute($search->getRoute());
        }

        $invoices = $invoiceRepository->findBySearch($search);

        return $this->render(
            'invoice/index.html.twig',
            [
                'formSearch' => $formSearch->createView(),
                'invoices' => $invoices,
                'search' => $search,
            ]
        );
    }

    /**
     * @Route("/new",
     *     name="app_invoice_new",
     *     methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $em, TranslatorInterface $translator): Response
    {
        try {
            $invoice = new Invoice();
        } catch (Exception $e) {
            $this->addFlash('danger', $translator->trans('notification.unable_to_create_invoice'));

            return $this->redirectToRoute('app_invoice_index');
        }
        $formEdit = $this->createForm(InvoiceType::class, $invoice);
        $formEdit->handleRequest($request);

        if ($formEdit->isSubmitted() && $formEdit->isValid()) {
            $em->persist($invoice);
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.invoice_added'));

            return $this->redirectToRoute('app_invoice_show', ['uuid' => $invoice->getUuid()]);
        }

        return $this->render(
            'invoice/new.html.twig',
            [
                'formEdit' => $formEdit->createView(),
            ]
        );
    }

    /**
     * @Route("/{uuid}/print",
     *     name="app_invoice_print",
     *     methods={"GET"})
     */
    public function print(InvoicePDF $generator, TranslatorInterface $translator, Invoice $invoice): BinaryFileResponse
    {
        $filename = tempnam(sys_get_temp_dir(), 'invoice-');

        $generator->build($invoice);
        $generator->Output($filename, 'F');

        /** @var Client $client */
        $client = $invoice->getClient();

        $response = new BinaryFileResponse($filename);
        $response->setContentDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            sprintf(
                '%s - %s %s - %s.pdf',
                $invoice->getIssueDate()->format('Y-m-d'),
                $translator->trans($invoice->getType()),
                $invoice->getNumberComplete(),
                strtoupper(iconv('UTF-8', 'ASCII//TRANSLIT', (string) $client->getCode()))
            )
        );

        return $response;
    }

    /**
     * @Route("/{uuid}", name="app_invoice_show", methods={"GET"})
     */
    public function show(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Invoice $invoice
    ): Response {
        if ($request->query->has('copy')) {
            try {
                /** @var Address $address */
                $address = $invoice->getAddress();

                $copyAddress = new Address();
                $copyAddress
                    ->setAddress($address->getAddress())
                    ->setCity($address->getCity())
                    ->setCountry($address->getCountry())
                    ->setName($address->getName())
                    ->setPostcode($address->getPostcode());
                $em->persist($copyAddress);

                $copyInvoice = new Invoice();
                $copyInvoice
                    ->setAddress($copyAddress)
                    ->setAmountExcludingTax($invoice->getAmountExcludingTax())
                    ->setAmountIncludingTax($invoice->getAmountIncludingTax())
                    ->setAmountPaid($invoice->getAmountPaid())
                    ->setClient($invoice->getClient())
                    ->setCredit($invoice->getCredit())
                    ->setComment($invoice->getComment())
                    ->setCommentInternal($invoice->getCommentInternal())
                    ->setDueDate(new DateTime('+30 days'))
                    ->setIssueDate(new DateTime())
                    ->setOrderNumber($invoice->getOrderNumber())
                    ->setTaxRate($invoice->getTaxRate())
                    ->setType($invoice->getType())
                    ->updateAmounts();
                $em->persist($copyInvoice);

                foreach ($invoice->getDetails() as $detail) {
                    $copyDetail = new InvoiceDetail();
                    $copyDetail
                        ->setAmountTotal($detail->getAmountTotal())
                        ->setAmountUnit($detail->getAmountUnit())
                        ->setDesignation($detail->getDesignation())
                        ->setInvoice($copyInvoice)
                        ->setQuantity($detail->getQuantity());
                    $em->persist($copyDetail);
                }

                $em->flush();

                $this->addFlash('success', $translator->trans('notification.invoice_copied'));

                return $this->redirectToRoute('app_invoice_edit', ['uuid' => $copyInvoice->getUuid()]);
            } catch (Exception $e) {
                return $this->redirectToRoute('app_invoice_show', ['uuid' => $invoice->getUuid()]);
            }
        }

        return $this->render(
            'invoice/show.html.twig',
            [
                'invoice' => $invoice,
            ]
        );
    }
}

templates/invoice/base.html.twig
{% extends 'base.html.twig' %}

{% set menuActive='invoice' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('invoice') }}
{% endblock %}

templates/invoice/delete.html.twig
{% extends 'invoice/base.html.twig' %}

{% block page_title %}{{ invoice.type|trans }} {{ invoice.number }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_invoice_show',{uuid:invoice.uuid}) }}" class="btn btn-outline-secondary">
        <span class="fa fa-list"></span>
        <span class="d-none d-md-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    {{ form_start(formDelete) }}
    <div class="mt-5">
        {{ form_widget(formDelete.confirmation) }}
    </div>
    <div class="mt-4">
        <button type="submit" class="btn btn-danger">
            <span class="fa fa-trash"></span>
            {{ 'action.delete'|trans }}
        </button>
        <a href="{{ path('app_invoice_show',{uuid:invoice.uuid}) }}" class="btn btn-outline-secondary">
            <span class="fa fa-times"></span>
            {{ 'action.cancel'|trans }}
        </a>
    </div>
    {{ form_end(formDelete) }}

{% endblock %}

templates/invoice/edit.html.twig
{% extends 'invoice/base.html.twig' %}

{% form_theme formEdit 'invoice/_fields.html.twig' %}

{% block page_title %}{{ invoice.type|trans }} {{ invoice.numberComplete }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_invoice_show',{uuid:invoice.uuid}) }}" class="btn btn-outline-secondary">
        <span class="fa fa-undo"></span>
        <span class="d-none d-md-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    {{ form_errors(formEdit) }}

    {{ form_start(formEdit) }}

    <div class="row mt-4">

        <div class="col-12 col-md-6">

            <fieldset>
                <legend class="mb-3">Informations</legend>
                {{ form_row(formEdit.client) }}
                {{ form_row(formEdit.type) }}
                {{ form_row(formEdit.issueDate) }}
                {{ form_row(formEdit.dueDate) }}
                {% if formEdit.supplierNumber is defined %}{{ form_row(formEdit.supplierNumber) }}{% endif %}
                {{ form_row(formEdit.orderNumber) }}
            </fieldset>

        </div>

        <div class="col-12 col-md-6">

            <fieldset>
                <legend class="mb-3">{{ formEdit.address.vars.label|trans }}</legend>
                <div>{{ form_widget(formEdit.address.name) }}</div>
                <div class="mt-2">{{ form_widget(formEdit.address.address) }}</div>
                <div class="row mt-2">
                    <div class="col-4 col-md-3">{{ form_widget(formEdit.address.postcode) }}</div>
                    <div class="col-8 col-md-9 pl-0">{{ form_widget(formEdit.address.city) }}</div>
                </div>
                <div class="mt-2">{{ form_widget(formEdit.address.country) }}</div>
                <div class="mt-2">{{ form_widget(formEdit.comment) }}</div>
                <div class="mt-2">{{ form_widget(formEdit.commentInternal) }}</div>
            </fieldset>

        </div>

    </div>

    <h2 class="mb-md-4 mt-5 text-truncate">{{ formEdit.details.vars.label|trans }}</h2>

    <div class="mb-5">
        <div class="d-none d-md-flex row border-bottom pb-2">
            <div class="col-6">{{ 'field.designation'|trans }}</div>
            <div class="col-2">{{ 'field.quantity'|trans }}</div>
            <div class="col-2">{{ 'field.amount_unit'|trans }}</div>
            <div class="col-2">{{ 'field.amount_excluding_tax'|trans }}</div>
        </div>
        {{ form_widget(formEdit.details) }}
        <div class="mt-3">
            <div class="btn-group btn-group-sm">
                <button type="button" class="btn btn-outline-primary js-detail-add">
                    <span class="fa fa-plus"></span>
                    {{ 'action.add'|trans }}
                </button>
            </div>
        </div>
        <div class="row mt-3 pt-2 border-top">
            {{ form_row(formEdit.amountExcludingTax) }}
            {{ form_row(formEdit.taxRate) }}
            {{ form_row(formEdit.taxAmount) }}
            {{ form_row(formEdit.amountIncludingTax) }}
            {{ form_row(formEdit.amountPaid) }}
        </div>
    </div>

    <div class="fixed-bottom bg-light border-top p-2 text-center">
        <button type="submit" class="btn btn-success">
            <span class="fa fa-save"></span>
            {{ 'action.save'|trans }}
        </button>
        <a href="{{ path('app_invoice_show',{uuid:invoice.uuid}) }}" class="btn btn-outline-secondary">
            <span class="fa fa-undo"></span>
            {{ 'action.cancel'|trans }}
        </a>
    </div>

    {{ form_end(formEdit) }}

{% endblock %}

templates/invoice/show.html.twig
{% extends 'invoice/base.html.twig' %}

{% block page_title %}{{ invoice.type|trans }} {{ invoice.numberComplete }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_invoice_index') }}" class="btn btn-outline-secondary">
        <span class="fa fa-list"></span>
        <span class="d-none d-md-inline">{{ 'action.back'|trans }}</span>
    </a>
    <a href="{{ path('app_invoice_new') }}" class="btn btn-outline-secondary">
        <span class="fa fa-plus"></span>
        <span class="d-none d-md-inline">{{ 'action.add'|trans }}</span>
    </a>
    <a href="{{ path('app_invoice_print',{uuid:invoice.uuid}) }}" class="btn btn-outline-primary">
        <span class="fa fa-print"></span>
        <span class="d-none d-md-inline">{{ 'action.print'|trans }}</span>
    </a>
    <a href="#"
       class="btn btn-outline-info"
       id="js-action-duplicate"
       data-confirm="{{ 'confirmation.duplicate_invoice'|trans }}"
       data-url="{{ path('app_invoice_show',{uuid:invoice.uuid,'copy':1}) }}">
        <span class="fa fa-copy"></span>
        <span class="d-none d-md-inline">{{ 'action.duplicate'|trans }}</span>
    </a>
    <a href="{{ path('app_invoice_edit',{uuid:invoice.uuid}) }}" class="btn btn-outline-primary">
        <span class="fa fa-pencil"></span>
        <span class="d-none d-md-inline">{{ 'action.edit'|trans }}</span>
    </a>
    <a href="{{ path('app_invoice_delete',{uuid:invoice.uuid}) }}" class="btn btn-outline-danger">
        <span class="fa fa-trash"></span>
        <span class="d-none d-md-inline">{{ 'action.delete'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div class="row">

        <div class="col-12 col-md-4">

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.number'|trans }}</div>
                <div>{{ invoice.type|trans }} {{ invoice.numberComplete }}</div>
            </div>

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.client'|trans }}</div>
                <div>
                    <a href="{{ path('app_client_show',{uuid:invoice.client.uuid}) }}">{{ invoice.client.name }}</a>
                </div>
            </div>

        </div>

        <div class="col-12 col-md-4">

            <div class="mt-2 mt-md-0">
                <div class="text-muted small">{{ 'field.issue_date'|trans }}</div>
                <div>{{ invoice.issueDate|localizeddate('full','none')|capitalize }}</div>
            </div>

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.due_date'|trans }}</div>
                <div>{{ invoice.dueDate|localizeddate('full','none')|capitalize }}</div>
            </div>

            {% if invoice.client.supplierNumber %}
                <div class="mt-2">
                    <div class="text-muted small">{{ 'field.supplier_number'|trans }}</div>
                    <div>{{ invoice.client.supplierNumber }}</div>
                </div>
            {% endif %}

            {% if invoice.orderNumber %}
                <div class="mt-2">
                    <div class="text-muted small">{{ 'field.order_number'|trans }}</div>
                    <div>{{ invoice.orderNumber }}</div>
                </div>
            {% endif %}

        </div>

        <div class="col-12 col-md-4 mt-2 mt-md-0">
            <div class="text-muted small">{{ 'field.address'|trans }}</div>
            <div>
                {{ invoice.address.name }}<br/>
                {{ invoice.address.address|nl2br }}<br/>
                {{ invoice.address.postcode }} {{ invoice.address.city }}<br/>
                {{ invoice.address.country|localizedcountry }}
            </div>
        </div>

        {% if invoice.comment|length>0 %}
            <div class="col-12 mt-2">
                <div class="text-muted small">{{ 'field.comment'|trans }}</div>
                <div>{{ invoice.comment|nl2br }}</div>
            </div>
        {% endif %}

        {% if invoice.commentInternal|length>0 %}
            <div class="col-12 mt-2">
                <div class="text-muted small">{{ 'field.internal_comment'|trans }}</div>
                <div>{{ invoice.commentInternal|nl2br }}</div>
            </div>
        {% endif %}

    </div>

    <div class="mt-4">
        <div class="d-none d-md-flex row mt-5">
            <div class="col-6"><strong>{{ 'field.designation'|trans }}</strong></div>
            <div class="col-2 text-right"><strong>{{ 'field.quantity'|trans }}</strong></div>
            <div class="col-2 text-right"><strong>{{ 'field.amount_unit'|trans }}</strong></div>
            <div class="col-2 text-right"><strong>{{ 'field.amount_excluding_tax'|trans }}</strong></div>
        </div>
        {% for detail in invoice.details %}
            <div class="mt-2 row border-top pt-2">
                <div class="col-12 col-md-6 text-truncate-under-md">{{ detail.designation|nl2br }}</div>
                <div class="col-12 col-md-2">
                    <div class="row">
                        <div class="col-6 d-md-none">{{ 'field.quantity'|trans }}</div>
                        <div class="col-6 col-md-12 text-right">{{ detail.quantity }}</div>
                    </div>
                </div>
                <div class="col-12 col-md-2">
                    <div class="row">
                        <div class="col-6 d-md-none">{{ 'field.amount_unit'|trans }}</div>
                        <div class="col-6 col-md-12 text-right">{{ detail.amountUnit|localizedcurrency(currency) }}</div>
                    </div>
                </div>
                <div class="col-12 col-md-2">
                    <div class="row">
                        <div class="col-6 d-md-none">{{ 'field.amount_excluding_tax'|trans }}</div>
                        <div class="col-6 col-md-12 text-right">{{ detail.amountTotal|localizedcurrency(currency) }}</div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="row border-top mt-2 pt-2">
            <div class="col-5 col-md-10 text-md-right">{{ 'field.amount_excluding_tax'|trans }}</div>
            <div class="col-7 col-md-2 text-right">{{ invoice.amountExcludingTax|localizedcurrency(currency) }}</div>
        </div>
        <div class="row mt-2">
            <div class="col-6 col-md-10 text-md-right">
                {{ 'field.tax_amount'|trans }}
                <span class="d-none d-md-inline">({{ invoice.taxRate|localizednumber('percent') }})</span>
            </div>
            <div class="col-6 col-md-2 text-right">{{ invoice.taxAmount|localizedcurrency(currency) }}</div>
        </div>
        <div class="row mt-2">
            <div class="col-6 col-md-10 text-md-right">
                <strong>{{ 'field.amount_including_tax'|trans }}</strong>
            </div>
            <div class="col-6 col-md-2 text-right">
                <strong>{{ invoice.amountIncludingTax|localizedcurrency(currency) }}</strong>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-6 col-md-10 text-md-right">
                {{ 'field.amount_paid'|trans }}
            </div>
            <div class="col-6 col-md-2 text-right">
                {{ invoice.amountPaid|localizedcurrency(currency) }}
            </div>
        </div>
    </div>

{% endblock %}