src/Entity/Task.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Helper\IdTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Table(name="app_task")
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    use IdTrait;
    use TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="tasks")
     */
    private $project;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $stop;

    /**
     * @ORM\Column(type="boolean")
     */
    private $onSite = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $unexpected = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $externalReference;

    public function __toString(): string
    {
        return (string) $this->name;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getStop(): ?\DateTimeInterface
    {
        return $this->stop;
    }

    public function setStop(?\DateTimeInterface $stop): self
    {
        $this->stop = $stop;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getOnSite(): bool
    {
        return $this->onSite;
    }

    public function setOnSite(bool $onSite): self
    {
        $this->onSite = $onSite;

        return $this;
    }

    public function getUnexpected(): bool
    {
        return $this->unexpected;
    }

    public function setUnexpected(bool $unexpected): self
    {
        $this->unexpected = $unexpected;

        return $this;
    }

    public function getExternalReference(): ?string
    {
        return $this->externalReference;
    }

    public function setExternalReference(?string $externalReference): self
    {
        $this->externalReference = $externalReference;

        return $this;
    }

    public function getDuration(): int
    {
        return $this->stop->getTimestamp() - $this->start->getTimestamp();
    }
}

src/Controller/TrackerController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Repository\TaskRepository;
use App\Service\TrackerManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tracker")
 */
class TrackerController extends AbstractController
{
    /**
     * @Route("/",
     *     name="app_tracker_index",
     *     methods={"GET"})
     */
    public function index(Request $request, TaskRepository $repository, TrackerManager $trackerManager): Response
    {
        if ($request->query->has('refresh')) {
            $trackerManager->importFromToggl();

            return $this->redirectToRoute('app_tracker_index');
        }

        $tasks = $repository->findBySearch();

        return $this->render(
            'tracker/index.html.twig',
            [
                'tasks' => $tasks,
            ]
        );
    }
}

templates/tracker/base.html.twig
{% extends 'base.html.twig' %}

{% set menuActive='tracker' %}

templates/tracker/index.html.twig
{% extends 'tracker/base.html.twig' %}

{% block page_title %}{{ 'menu.tracker'|trans }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_tracker_index',{refresh:1}) }}" class="btn btn-outline-primary">
        <span class="fa fa-refresh"></span>
        <span class="d-none d-md-inline">{{ 'action.refresh'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div id="page-tracker-index">

        <table class="table table-responsive-sm mt-4">
            <thead>
            <tr>
                <th>{{ 'field.name'|trans }}</th>
                <th>{{ 'field.project'|trans }}</th>
                <th>{{ 'field.client'|trans }}</th>
                <th>{{ 'field.date'|trans }}</th>
                <th>{{ 'field.start'|trans }}</th>
                <th>{{ 'field.stop'|trans }}</th>
                <th>{{ 'field.duration'|trans }}</th>
                <th>{{ 'field.unexpected'|trans }}</th>
                <th>{{ 'field.on_site'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.project }}</td>
                    <td>{{ task.project.client }}</td>
                    <td>{{ task.start|localizeddate('short','none') }}</td>
                    <td>{{ task.start|localizeddate('none','short') }}</td>
                    <td>{{ task.stop|localizeddate('none','short') }}</td>
                    <td>{{ task.duration|localizedduration('short') }}</td>
                    <td class="text-center">
                        {% if task.unexpected %}
                            <span class="fa fa-warning"></span>
                        {% endif %}
                    </td>
                    <td class="text-center">
                        {% if task.onSite %}
                            <span class="fa fa-building"></span>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}