src/Entity/RateInterface.php
<?php

declare(strict_types=1);

namespace App\Entity;

interface RateInterface
{
    public function getHourlyRateOnSite(): ?float;

    public function getHourlyRateOffSite(): ?float;
}

src/Form/Type/ClientType.php
<?php

declare(strict_types=1);

namespace App\Form\Type;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ClientType.
 */
class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'name',
                TextType::class,
                [
                    'label' => 'field.name',
                    'required' => true,
                ]
            )
            ->add(
                'code',
                TextType::class,
                [
                    'label' => 'field.code',
                    'required' => true,
                ]
            )
            ->add(
                'active',
                ChoiceType::class,
                [
                    'choices' => [
                        'yes' => 1,
                        'no' => 0,
                    ],
                    'label' => 'field.active',
                    'required' => true,
                ]
            )
            ->add(
                'comment',
                TextareaType::class,
                [
                    'label' => 'field.comment',
                    'required' => false,
                ]
            )
            ->add(
                'supplierNumber',
                TextType::class,
                [
                    'label' => 'field.supplier_number',
                    'required' => false,
                ]
            )
            ->add(
                'vatNumber',
                TextType::class,
                [
                    'label' => 'field.vat_number',
                    'required' => false,
                ]
            )
            ->add(
                'addressPrimary',
                AddressType::class,
                [
                    'label' => 'primary_address',
                    'required' => true,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => Client::class,
            ]
        );
    }
}

src/Controller/ClientController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Client;
use App\Entity\ClientRate;
use App\Form\Type\ClientDeleteType;
use App\Form\Type\ClientRateDeleteType;
use App\Form\Type\ClientRateType;
use App\Form\Type\ClientSearchType;
use App\Form\Type\ClientType;
use App\Repository\ClientRepository;
use App\Service\SearchManager;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/client")
 * @IsGranted("ROLE_ADMIN")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/{uuid}/delete",
     *     name="app_client_delete",
     *     methods={"GET", "POST"})
     */
    public function delete(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Client $client
    ): Response {
        if (count($client->getInvoices()) > 0) {
            return $this->redirectToRoute('app_client_show', ['uuid' => $client->getUuid()]);
        }

        $form = $this->createForm(ClientDeleteType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->remove($client);
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.client_removed'));

            return $this->redirectToRoute('app_client_index');
        }

        return $this->render(
            'client/delete.html.twig',
            [
                'form' => $form->createView(),
                'client' => $client,
            ]
        );
    }

    /**
     * @Route("/{uuid}/edit",
     *     name="app_client_edit",
     *     methods={"GET", "POST"})
     */
    public function edit(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Client $client
    ): Response {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.client_updated'));

            return $this->redirectToRoute('app_client_show', ['uuid' => $client->getUuid()]);
        }

        return $this->render(
            'client/edit.html.twig',
            [
                'client' => $client,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/",
     *     name="app_client_index",
     *     methods={"GET", "POST"})
     */
    public function index(Request $request, SearchManager $sm, ClientRepository $clientRepository): Response
    {
        $search = $sm->find($this->getUser(), 'app_client_index');

        $formSearch = $this->createForm(ClientSearchType::class);

        if ($sm->handleRequest($search, $request, $formSearch)) {
            return $this->redirectToRoute($search->getRoute());
        }

        $clients = $clientRepository->findBySearch($search);

        return $this->render(
            'client/index.html.twig',
            [
                'clients' => $clients,
                'formSearch' => $formSearch->createView(),
                'search' => $search,
            ]
        );
    }

    /**
     * @Route("/info",
     *     name="app_client_info",
     *     methods={"GET"})
     */
    public function info(Request $request, ClientRepository $repository): Response
    {
        $client = $repository->findOneBy(['uuid' => $request->query->get('client')]);

        return new JsonResponse($client);
    }

    /**
     * @Route("/new",
     *     name="app_client_new", methods={"GET", "POST"})
     */
    public function new(Request $request, TranslatorInterface $translator): Response
    {
        try {
            $client = new Client();
        } catch (\Exception $e) {
            $this->addFlash('danger', $translator->trans('notification.unable_to_create_client'));

            return $this->redirectToRoute('app_client_index');
        }
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($client);
            $em->flush();

            return $this->redirectToRoute('app_client_index');
        }

        return $this->render(
            'client/new.html.twig',
            [
                'client' => $client,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/rate/{uuid}/delete",
     *     name="app_client_rate_delete",
     *     methods={"GET", "POST"})
     */
    public function rateDelete(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        ClientRate $rate
    ): Response {
        /** @var Client $client */
        $client = $rate->getClient();

        $formDelete = $this->createForm(ClientRateDeleteType::class, $rate);
        $formDelete->handleRequest($request);

        if ($formDelete->isSubmitted() && $formDelete->isValid()) {
            $em->remove($rate);
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.client_rate_removed'));

            return $this->redirectToRoute('app_client_show', ['uuid' => $client->getUuid()]);
        }

        return $this->render(
            'client/rate_delete.html.twig',
            [
                'formDelete' => $formDelete->createView(),
                'client' => $client,
            ]
        );
    }

    /**
     * @Route("/rate/{uuid}/edit",
     *     name="app_client_rate_edit",
     *     methods={"GET", "POST"})
     */
    public function rateEdit(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        ClientRate $rate
    ): Response {
        /** @var Client $client */
        $client = $rate->getClient();

        $formEdit = $this->createForm(ClientRateType::class, $rate);
        $formEdit->handleRequest($request);

        if ($formEdit->isSubmitted() && $formEdit->isValid()) {
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.client_rate_updated'));

            return $this->redirectToRoute('app_client_show', ['uuid' => $client->getUuid()]);
        }

        return $this->render(
            'client/rate_edit.html.twig',
            [
                'formEdit' => $formEdit->createView(),
                'client' => $client,
            ]
        );
    }

    /**
     * @Route("/rate/new/{uuid}",
     *     name="app_client_rate_new",
     *     methods={"GET", "POST"})
     */
    public function rateNew(
        Request $request,
        EntityManagerInterface $em,
        TranslatorInterface $translator,
        Client $client
    ): Response {
        $rate = new ClientRate();
        $rate->setClient($client);

        $formEdit = $this->createForm(ClientRateType::class, $rate);
        $formEdit->handleRequest($request);

        if ($formEdit->isSubmitted() && $formEdit->isValid()) {
            $em->persist($rate);
            $em->flush();

            $this->addFlash('success', $translator->trans('notification.client_rate_added'));

            return $this->redirectToRoute('app_client_show', ['uuid' => $client->getUuid()]);
        }

        return $this->render(
            'client/rate_new.html.twig',
            [
                'formEdit' => $formEdit->createView(),
                'client' => $client,
            ]
        );
    }

    /**
     * @Route("/{uuid}",
     *     name="app_client_show",
     *     methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render(
            'client/show.html.twig',
            [
                'client' => $client,
            ]
        );
    }
}

templates/client/base.html.twig
{% extends 'base.html.twig' %}

{% set menuActive='client' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('client') }}
{% endblock %}

templates/client/delete.html.twig
{% extends 'client/base.html.twig' %}

{% block body %}

    <div id="page-client-delete">

        <div class="d-flex flex-row align-items-center">
            <h2 class="flex-grow-1 mb-0 text-truncate">{{ client.name }}</h2>
            <div class="btn-group ml-2">
                <a href="{{ path('app_client_index') }}" class="btn btn-outline-secondary">
                    <span class="fa fa-list"></span>
                    <span class="d-none d-md-inline">{{ 'action.back'|trans }}</span>
                </a>
                <a href="{{ path('app_client_edit',{uuid:client.uuid}) }}" class="btn btn-primary">
                    <span class="fa fa-undo"></span>
                    <span class="d-none d-md-inline">{{ 'action.cancel'|trans }}</span>
                </a>
            </div>
        </div>

        {{ form_start(form) }}
        <div class="mt-5">
            {{ form_widget(form.confirmation) }}
        </div>
        <div class="mt-4">
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-trash"></span>
                {{ 'action.delete'|trans }}
            </button>
        </div>
        {{ form_end(form) }}

    </div>

{% endblock %}

templates/client/edit.html.twig
{% extends 'client/base.html.twig' %}

{% block body %}

    <div id="page-client-edit">

        <div class="d-flex flex-row align-items-center">
            <h2 class="flex-grow-1 mb-0 text-truncate">{{ client.name }}</h2>
            <div class="btn-group">
                <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
                    <span class="fa fa-undo"></span>
                    <span class="d-none d-sm-inline">{{ 'action.back'|trans }}</span>
                </a>
            </div>
        </div>

        {{ form_start(form,{attr:{class:'mt-4'}}) }}

        {{ form_row(form.code) }}
        {{ form_row(form.name) }}
        {{ form_row(form.vatNumber) }}
        {{ form_row(form.supplierNumber) }}
        {{ form_row(form.comment) }}
        {{ form_row(form.active) }}

        <h3 class="mb-3 mt-5">{{ form.addressPrimary.vars.label|trans }}</h3>

        {{ form_row(form.addressPrimary.name) }}
        {{ form_row(form.addressPrimary.address) }}
        {{ form_row(form.addressPrimary.postcode) }}
        {{ form_row(form.addressPrimary.city) }}
        {{ form_row(form.addressPrimary.country) }}

        <div class="mt-5">
            <button type="submit" class="btn btn-success">
                <span class="fa fa-save"></span>
                {{ 'action.save'|trans }}
            </button>
            <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
                <span class="fa fa-undo"></span>
                {{ 'action.cancel'|trans }}
            </a>
        </div>

        {{ form_end(form) }}

    </div>

{% endblock %}

templates/client/index.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ 'title.client_list'|trans }}{% endblock %}

{% block page_menu %}
    <a href="#" class="btn btn-outline-secondary" data-toggle="modal" data-target=".filters">
        <span class="fa fa-filter"></span>
        <span class="d-none d-md-inline">{{ 'filters'|trans }}</span>
        {% if search.filter|length>0 %}
            <small>({{ search.filter|length }})</small>
        {% endif %}
    </a>
    <a href="{{ path('app_client_new') }}" class="btn btn-outline-primary">
        <span class="fa fa-plus"></span>
        <span class="d-none d-md-inline">{{ 'action.add'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <table class="table mt-4">
        <thead>
        <tr>
            <th>{% include '_sort.html.twig' with {code:'name',name:'field.name',search:search} only %}</th>
            <th class="d-none d-sm-table-cell">{% include '_sort.html.twig' with {code:'status',name:'field.status',search:search} only %}</th>
            <th class="d-none d-lg-table-cell">{% include '_sort.html.twig' with {code:'postcode',name:'field.postcode',search:search} only %}</th>
            <th class="d-none d-sm-table-cell">{% include '_sort.html.twig' with {code:'city',name:'field.city',search:search} only %}</th>
        </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>
                    <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="flex-grow-1">
                        {{ client.name }}
                    </a>
                </td>
                <td class="d-none d-sm-table-cell">
                    {% if client.active %}
                        <span class="badge badge-success">{{ 'active'|trans }}</span>
                    {% else %}
                        <span class="badge badge-light">{{ 'inactive'|trans }}</span>
                    {% endif %}
                </td>
                <td class="d-none d-lg-table-cell">{{ client.addressPrimary.postcode }}</td>
                <td class="d-none d-sm-table-cell">{{ client.addressPrimary.city }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="p-5 text-muted text-center">{{ 'no_results_for_your_search'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include '_pagination.html.twig' with {search:search,results:clients|length} only %}

    {% include '_filters.html.twig' with {formSearch:formSearch,search:search} only %}

{% endblock %}

templates/client/new.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ 'title.client_add'|trans }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_client_index') }}" class="btn btn-outline-secondary">
        <span class="fa fa-list"></span>
        <span class="d-none d-sm-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    {{ form_start(form,{attr:{class:'mt-4'}}) }}

    {{ form_row(form.code) }}
    {{ form_row(form.name) }}
    {{ form_row(form.vatNumber) }}
    {{ form_row(form.supplierNumber) }}
    {{ form_row(form.comment) }}
    {{ form_row(form.active) }}

    <h3 class="mb-3 mt-5">{{ form.addressPrimary.vars.label|trans }}</h3>

    {{ form_row(form.addressPrimary.name) }}
    {{ form_row(form.addressPrimary.address) }}
    {{ form_row(form.addressPrimary.postcode) }}
    {{ form_row(form.addressPrimary.city) }}
    {{ form_row(form.addressPrimary.country) }}

    <div class="mt-5">
        <button type="submit" class="btn btn-success">
            <span class="fa fa-save"></span>
            {{ 'action.save'|trans }}
        </button>
        <a href="{{ path('app_invoice_index') }}" class="btn btn-outline-secondary">
            <span class="fa fa-undo"></span>
            {{ 'action.cancel'|trans }}
        </a>
    </div>

    {{ form_end(form) }}

{% endblock %}

templates/client/rate_delete.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ 'title.client_rate_delete'|trans }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
        <span class="fa fa-undo"></span>
        <span class="d-none d-sm-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div class="mt-5">

        {{ form_start(formDelete) }}
        {{ form_widget(formDelete) }}
        <div class="mt-5">
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-trash"></span>
                {{ 'action.delete'|trans }}
            </button>
            <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
                <span class="fa fa-undo"></span>
                {{ 'action.cancel'|trans }}
            </a>
        </div>
        {{ form_end(formDelete) }}

    </div>

{% endblock %}

templates/client/rate_edit.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ 'title.client_rate_edit'|trans }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
        <span class="fa fa-undo"></span>
        <span class="d-none d-sm-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div class="mt-5">

        {{ form_start(formEdit) }}
        {{ form_widget(formEdit) }}
        <div class="mt-5">
            <button type="submit" class="btn btn-success">
                <span class="fa fa-save"></span>
                {{ 'action.save'|trans }}
            </button>
            <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
                <span class="fa fa-undo"></span>
                {{ 'action.cancel'|trans }}
            </a>
        </div>
        {{ form_end(formEdit) }}

    </div>

{% endblock %}

templates/client/rate_new.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ 'title.client_rate_add'|trans }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
        <span class="fa fa-undo"></span>
        <span class="d-none d-sm-inline">{{ 'action.back'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div class="mt-5">

        {{ form_start(formEdit) }}
        {{ form_widget(formEdit) }}
        <div class="mt-5">
            <button type="submit" class="btn btn-success">
                <span class="fa fa-save"></span>
                {{ 'action.save'|trans }}
            </button>
            <a href="{{ path('app_client_show',{uuid:client.uuid}) }}" class="btn btn-outline-secondary">
                <span class="fa fa-undo"></span>
                {{ 'action.cancel'|trans }}
            </a>
        </div>
        {{ form_end(formEdit) }}

    </div>

{% endblock %}

templates/client/show.html.twig
{% extends 'client/base.html.twig' %}

{% block page_title %}{{ client.name }}{% endblock %}

{% block page_menu %}
    <a href="{{ path('app_client_index') }}" class="btn btn-outline-secondary">
        <span class="fa fa-list"></span>
        <span class="d-none d-md-inline">{{ 'action.back'|trans }}</span>
    </a>
    <a href="{{ path('app_client_edit',{uuid:client.uuid}) }}" class="btn btn-outline-primary">
        <span class="fa fa-pencil"></span>
        <span class="d-none d-md-inline">{{ 'action.edit'|trans }}</span>
    </a>
{% endblock %}

{% block body %}

    <div class="row">

        <div class="col-12 col-sm-6 col-lg-4">

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.name'|trans }}</div>
                <div>{{ client.name }}</div>
            </div>

            {% if client.code %}
                <div class="mt-2">
                    <div class="text-muted small">{{ 'field.code'|trans }}</div>
                    <div>{{ client.code }}</div>
                </div>
            {% endif %}

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.status'|trans }}</div>
                <div>
                    {% if client.active %}
                        <span class="badge badge-success">{{ 'active'|trans }}</span>
                    {% else %}
                        <span class="badge badge-light">{{ 'inactive'|trans }}</span>
                    {% endif %}
                </div>
            </div>

        </div>

        <div class="col-12 col-sm-6 col-lg-4">

            <div class="mt-2">
                <div class="text-muted small">{{ 'primary_address'|trans }}</div>
                <div>
                    {{ client.addressPrimary.name }}<br/>
                    {{ client.addressPrimary.address|nl2br }}<br/>
                    {{ client.addressPrimary.postcode }} {{ client.addressPrimary.city }}<br/>
                    {{ client.addressPrimary.country|localizedcountry }}
                </div>
            </div>

        </div>

        <div class="col-12 col-sm-6 col-lg-4">

            {% if client.vatNumber %}
                <div class="mt-2">
                    <div class="text-muted small">{{ 'field.vat_number'|trans }}</div>
                    <div>{{ client.vatNumber }}</div>
                </div>
            {% endif %}

            {% if client.supplierNumber %}
                <div class="mt-2">
                    <div class="text-muted small">{{ 'field.supplier_number'|trans }}</div>
                    <div>{{ client.supplierNumber }}</div>
                </div>
            {% endif %}

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.creation'|trans }}</div>
                <div>{{ client.createdAt|localizeddate('long','short') }}</div>
            </div>

            <div class="mt-2">
                <div class="text-muted small">{{ 'field.lastUpdate'|trans }}</div>
                <div>{{ client.updatedAt|localizeddate('long','short') }}</div>
            </div>

        </div>

    </div>

    <div class="row">

        <div class="col-md-6">

            <h3 class="mt-5">{{ 'rates'|trans }}</h3>

            <table class="table table-responsive-sm mt-3">
                <colgroup>
                    <col/>
                    <col/>
                    <col/>
                    <col width="1"/>
                </colgroup>
                <thead class="text-nowrap">
                <tr>
                    <th>{{ 'field.start'|trans }}</th>
                    <th>{{ 'field.on_site'|trans }}</th>
                    <th>{{ 'field.off_site'|trans }}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for rate in client.rates %}
                    <tr>
                        <td class="align-middle">{{ rate.startedAt|localizeddate('short','none') }}</td>
                        <td class="align-middle">{{ rate.hourlyRateOnSite|localizedcurrency('EUR') }}</td>
                        <td class="align-middle">{{ rate.hourlyRateOffSite|localizedcurrency('EUR') }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ path('app_client_rate_edit',{uuid:rate.uuid}) }}"
                                   class="btn btn-outline-primary">
                                    <span class="fa fa-pencil"></span>
                                </a>
                                <a href="{{ path('app_client_rate_delete',{uuid:rate.uuid}) }}"
                                   class="btn btn-outline-danger">
                                    <span class="fa fa-trash"></span>
                                </a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4" class="p-5 text-center text-muted">{{ 'no_results_for_your_search'|trans }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div>
                <a href="{{ path('app_client_rate_new',{uuid:client.uuid}) }}" class="btn btn-outline-primary">
                    <span class="fa fa-plus"></span>
                    {{ 'action.add'|trans }}
                </a>
            </div>

        </div>

        <div class="col-md-6">

            <h3 class="mt-5">{{ 'projects'|trans }}</h3>

            <div class="list-group mt-3">
                {% for project in client.projects %}
                    <a href="{{ path('app_project_show',{uuid:project.uuid}) }}"
                       class="list-group-item list-group-item-action">
                        <div><strong>{{ project }}</strong></div>
                        <div>
                            {% if project.active %}
                                <span class="badge badge-success">{{ 'active'|trans }}</span>
                            {% else %}
                                <span class="badge badge-danger">{{ 'inactive'|trans }}</span>
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            </div>

        </div>

    </div>

{% endblock %}